/**
MANAF - 2019B3A70351P
ADARSH - 2019B3A70443P
NISHANT - 2019B3A70381P
**/
#ifndef COMPILER_DECLARE_ARRAY_STATEMENT_H
#define COMPILER_DECLARE_ARRAY_STATEMENT_H

#include "ast.h"

DeclareArrayVariableStatementNode *create_declare_array_statement_node();

#endif //COMPILER_DECLARE_ARRAY_STATEMENT_H
